version: '3.9'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: test_diary_app
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -ptestpass || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db-init/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_USER: testuser
      DB_PASSWORD: testpass
      DB_NAME: test_diary_app
    command: ["./wait-for-mysql.sh", "pytest", "test_app.py", "-v", "--tb=short", "--cov=app", "--cov-report=xml"]

volumes:
  mysql_data:
