version: '3.8'

services:
  app:
    image: diary_app:latest
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=diary_db
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: diary_db
    ports:
      - "3306:3306"
    volumes:
      - ./db-init/init.sql:/docker-entrypoint-initdb.d/init.sql
