name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: test_diary_app
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpass
        options: >-
          --health-cmd "mysqladmin ping -u root -p${MYSQL_ROOT_PASSWORD}"
          --health-interval 5s
          --health-timeout 10s
          --health-retries 20
        ports:
          - 3306:3306

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Wait for MySQL
      run: |
        for i in {1..30}; do
          if mysqladmin ping -h mysql -u root -prootpassword --silent; then
            echo "MySQL is ready"
            break
          fi
          echo "Waiting for MySQL... ($i/30)"
          sleep 2
        done
        if [ $i -eq 30 ]; then
          echo "MySQL failed to start"
          exit 1
        fi

    - name: Initialize database
      run: |
        mysql -h mysql -u root -prootpassword test_diary_app < db-init/init.sql

    - name: Run tests
      env:                             
        DB_HOST: mysql
        DB_USER: testuser
        DB_PASSWORD: testpass
        DB_NAME: test_diary_app
      run: |
        pytest test_app.py -v --tb=short --cov=app --cov-report=xml
