name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpassword
          MYSQL_DATABASE: diary_db
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpass
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Initialize database
      run: |
        mysql --host=127.0.0.1 --port=3306 --user=testuser --password=testpass diary_db < db-init/init.sql
      env:
        MYSQL_PWD: testpass

    - name: Run tests
      run: |
        pytest test_app.py
      env:
        DB_HOST: 127.0.0.1
        DB_USER: testuser
        DB_PASSWORD: testpass
        DB_NAME: diary_db
